
quake = {}

LUMP_ENTITIES		= 0
LUMP_TEXTURES		= 1
LUMP_PLANES			= 2
LUMP_NODES			= 3
LUMP_LEAFS			= 4
LUMP_LEAF_FACES		= 5
LUMP_LEAF_BRUSHES	= 6
LUMP_MODELS			= 7
LUMP_BRUSHES		= 8
LUMP_BRUSH_SIDES	= 9
LUMP_VERTEXES		= 10
LUMP_MESH_VERTEXES	= 11
LUMP_EFFECTS		= 12
LUMP_FACES			= 13
LUMP_LIGHTMAPS		= 14
LUMP_LIGHTVOLS		= 15
LUMP_VISDATA		= 16

BSP_MAGIC			= "IBSP"
BSP_VERSION			= 0x2E

BSP_LUMP_COUNT		= LUMP_VISDATA +1

TYPE_POLYGON		= 1
TYPE_PATCH			= 2
TYPE_MESH			= 3
TYPE_BILLBOARD		= 4
